apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: influxdb
  namespace: default
  finalizers:
  - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: https://kubernetes.default.svc
    namespace: default
  project: default
  source:
    chart: influxdata/influxdb
    repoURL: https://helm.influxdata.com/
    targetRevision: 4.9.14
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
